### PR TITLE
Fix textView display

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**
@quozl @chimosky @srevinsaju @JuiP Please review.

### CODE REVIEW

**Comment by quozl** [comment]
* [x] doesn't work, fails to start,
* [x] opportunity to place the colour arguments for Gdk.RGBA in the line that creates it,

**Comment by Saumya-Mishra9129** [comment]
> doesn't work, fails to start,

That was a reckless mistake. Fixed in 4ae5db3. Thanks @quozl Please review.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.

Fixes https://github.com/sugarlabs/story/issues/16.

However, your method to fix has problems;
* [ ] the text contrast is too low; in all other cases in Sugar the text is black against white, or white against black, to maximise contrast,
* [ ] the text is right up against the colour change,
* [ ] the caret text insertion cursor is practically invisible when at the start of a line,

I think it would be better to have an outline in black around the entry widget, with a small border inside.  Top left corner

```text
00000000
01111111
01000000
01022222
```

Key; (0) canvas background white, (1) outline in black, (2) text as black on white.

Also, unrelated to your change, clicking in the text, pressing `.` then enter, causes the text insertion cursor to jump to the end of the text;

Screenshot_uff_2020-08-08_09:18:09

**Comment by Saumya-Mishra9129** [comment]
@quozl Please review 6ac9215. 
I couldn't find a way to change color of border around a scrolled window. However it looks way better than it was before to me.

Screenshot from 2020-08-09 22-10-34

**Pull request merged**
