### PR TITLE
TelepathyGLib, Python3 ports, deprecation fixes [tested, GCI]

### PR DESCRIPTION
**Pull request by srevinsaju**
A combined pull request for Python3 port, TelepathyGLib, and deprecation errors
- [x] Port to Python3
- [x] Test on Linux DEs
- [x] Test on Sugar DE
- [x] Test on Sugar SOAS
- [x] Fix Deprecation
- [ ] Test Collaboration ?

Screenshot_20191212_150038
Screenshot_20191212_150146

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Good progress.  However,

* [x] StoryActivity.py has not been ported to TelepathyGLib,
* [x] collabwrapper.py has ended up different to our [master copy](https://github.com/sugarlabs/collabwrapper/blob/master/collabwrapper.py), why?

**Comment by srevinsaju** [comment]
> * [x]  StoryActivity.py has not been ported to TelepathyGLib,
> * [x]  collabwrapper.py : Updated to latest version

**Comment by quozl** [comment]
Thanks.  Reviewed.  Good progress.  Please continue with the test and let me know the result.

**Comment by quozl** [comment]
Collaboration is unfinished, according to a comment in the source.

**Comment by quozl** [comment]
Tested.

* [ ] warnings from GObject.source_remove at line 530 of game.py,
* [ ] pressing the mouth icon to play text doesn't work because of espeak use; espeak has been replaced, we now use sugar3.speech API.

**Comment by srevinsaju** [comment]
ok @Quozl espeak worked on my system, will replace that with sugar3.speech as it might be uniform throughout. thanks for reviewing, will make necessary changes

**Comment by srevinsaju** [comment]
with https://github.com/sugarlabs/story/pull/15/commits/f2a0cbac0f8ec22c46b040cf213a8730ef15ecae and https://github.com/sugarlabs/story/pull/15/commits/2c0e2feb6abb5b9186b8bfb0ec672e3136b78875 , its ported to sugar3.speech, but it creates the following warnings, I so far don't know how to correct them, but it works successfully.

The warnings :
```
(sugar-activity3:6229): GStreamer-WARNING **: 14:44:18.002: gstpad.c:5204:store_sticky_event:<espeak:src> Sticky event misordering, got 'caps' before 'stream-start'

(sugar-activity3:6229): GStreamer-WARNING **: 14:44:18.002: gstpad.c:5204:store_sticky_event:<sink:proxypad0> Sticky event misordering, got 'caps' before 'stream-start'

(sugar-activity3:6229): GStreamer-WARNING **: 14:44:18.002: gstpad.c:5204:store_sticky_event:<autoaudiosink0-actual-sink-pulse:sink> Sticky event misordering, got 'caps' before 'stream-start'

(sugar-activity3:6229): GStreamer-WARNING **: 14:44:18.003: gstpad.c:5204:store_sticky_event:<autoaudiosink0:sink> Sticky event misordering, got 'caps' before 'stream-start'

```

**Comment by quozl** [comment]
We've seen those warnings before.  They are probably caused by bitrot of the plugin, which hasn't been changed even though GStreamer has.  Let me know if you'd like to work on that.  https://github.com/sugarlabs/gst-plugins-espeak

**Comment by quozl** [comment]
Thanks.

**Pull request merged**
