### PR TITLE
Collaboration refactoring to use CollabWrapper

### PR DESCRIPTION
**Pull request by erilyth**
Move to the CollabWrapper offered by @samdroid-apps, https://github.com/samdroid-apps/collabwrapper

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Heh github decided to cc me into this.  It looks really good.  But remember to add the standalone version.  I fixed up the guide for how to do that and put it here:  https://github.com/samdroid-apps/collabwrapper

**Comment by erilyth** [comment]
I added 'from collabwrapper.collabwrapper import CollabWrapper' as the alternative import. Is this fine?

**Comment by samdroid-apps** [comment]
Yep, but you need to add the submodule, right now it isn't included in the commit.

**Comment by erilyth** [comment]
@samdroid-apps done :)

**Pull request merged**
